language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lerenah/psychic-potato -f Dockerfile.dev .

script:
  - docker run -e CI=true lerenah/psychic-potato npm run test -- --coverage